version: 2.1
jobs:
  build:
    environment:
      APP_NAME: idea-docker
      TAG_NAME: nrmancuso/idea-docker:latest
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/$APP_NAME.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/$APP_NAME.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=$APP_NAME -t $TAG_NAME .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/$APP_NAME.tar $APP_NAME
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/$APP_NAME.tar
#      - deploy:
#          name: Push application Docker image
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#              login="$(aws ecr get-login)"
#              ${login}
#              docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
#              docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
#            fi

workflows:
  build:
    jobs:
      - build